# Generated by Django 3.1.14 on 2022-08-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=25, verbose_name='Русское имя')),
                ('name_en', models.TextField(blank=True, max_length=25, verbose_name='Английское имя')),
                ('name_jp', models.TextField(blank=True, max_length=25, verbose_name='Японское имя')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Название картинки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True, verbose_name='Широта')),
                ('low', models.FloatField(null=True, verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(null=True, verbose_name='Время включения')),
                ('disappeared_at', models.DateTimeField(null=True, verbose_name='Время отключения')),
                ('level', models.IntegerField(null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(null=True, verbose_name='Прочность')),
                ('defencer', models.IntegerField(null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(null=True, verbose_name='стамина')),
                ('pokemon_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_name', to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
