# Generated by Django 3.1.14 on 2022-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='next_evolution',
            field=models.CharField(blank=True, max_length=25, verbose_name='Имя следующей эволюции'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.CharField(blank=True, max_length=25, verbose_name='Имя предыдущий эволюции'),
        ),
    ]
