# Generated by Django 3.1.14 on 2022-09-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20220924_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='test_1',
            field=models.ManyToManyField(related_name='_pokemon_test_1_+', to='pokemon_entities.Pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Русское имя'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name_en',
            field=models.CharField(max_length=25, unique=True, verbose_name='Английское имя'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name_jp',
            field=models.CharField(max_length=25, unique=True, verbose_name='Японское имя'),
        ),
    ]
