# Generated by Django 3.1.14 on 2022-11-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20221104_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='progenitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='Предшественник'),
        ),
    ]
