# Generated by Django 3.1.14 on 2022-10-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20220930_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='test_1',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_connections',
            field=models.ManyToManyField(related_name='_pokemon_pokemon_connections_+', to='pokemon_entities.Pokemon'),
        ),
    ]
