# Generated by Django 3.1.14 on 2022-10-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20221004_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pokemon_entities',
            new_name='pokemon',
        ),
    ]
