# Generated by Django 3.1.14 on 2022-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20221007_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_connections',
            field=models.ManyToManyField(related_name='_pokemon_pokemon_connections_+', to='pokemon_entities.Pokemon', verbose_name='Эволюции покемона'),
        ),
    ]
